### ISSUE TITLE
Namespace violation

### ISSUE THREAD

**Issue by dereuromark** [jadb/cakephp-monolog#11]
You seem to violate the namespace of composer:

```
cakephp/monolog
```

The vendor name belongs to CakePHP.

See the composer docs:

> If you don't know what to use as a vendor name, your GitHub username is usually a good bet. While package names are case insensitive, the convention is all lowercase and dashes for word separation.

So in your case I recommend

```
jadb/cakephp-monolog
```

as per convention.

As we all do ;)
- https://github.com/josegonzalez/cakephp-csvview
- https://github.com/dereuromark/cakephp-queue
- https://github.com/renan/CakePHP-XHProf as cakephp-xhprof

You should then delete the wrongly created packagist entry. And resubmit the correct one.

**Comment by dereuromark** [comment]
When this is fixed, we can add it to https://github.com/dereuromark/awesome-cakephp by the way.

**Comment by jadb** [comment]
Ok, I fixed the package name and created a new [packagist entry](http://packagist.org/packages/jadb/cakephp-monolog) for it.

I did not delete the old package yet because it's not appearing in search (not sure why yet) and would make it difficult for current users of the package to find the new one (even if I added it to the README).

Maybe you can add it to awesome-cakephp now?

**Comment by dereuromark** [comment]
You can mark packages as abandoned in packagist and link to the correct new one by the way.

PS: feel free to make a PR.

**Comment by jadb** [comment]
I tried that but didn't work - it kept linking to itself (maybe because it the same git repo).

**Comment by dereuromark** [comment]
You will then have to open a ticket in their github repo and ask the maintainer to manually delete this:

```
https://packagist.org/packages/cakephp/monolog
```

**Comment by jadb** [comment]
Was planning on doing that but waiting for the new package name to appear in search first - trying not to make it too hard on people who are using the package already.

**Comment by dereuromark** [comment]
Added/Fixed in https://github.com/dereuromark/awesome-cakephp/commit/e4d05b243120f28107fd90de808ef4b6ecab5664

You can have both parallel usually.
Either way you need to remove your violation namespace as soon as possible :)

**Comment by jadb** [comment]
Will sure do. 

I have other packages I believe could be added to both the Cake2 and Cake3 list - should I create a PR for each?

**Comment by dereuromark** [comment]
Not if its both 2 and 3. I will merge to cake3 then automatically afterwards

**Comment by jadb** [comment]
Ok, understood for plugins that work on both versions.

But I mean for every plugin a new PR?

**Comment by dereuromark** [comment]
Yes, and please mention if its for 2.x and 3.x or just 2.x.

**Comment by dereuromark** [comment]
PS: You should delete https://packagist.org/packages/cakephp/monolog (or ask them for deleting it).

**Comment by dereuromark** [comment]
Update: You can now just "mark it as abandoned" and link to the actual correct packagist repo.

**Comment by jadb** [comment]
Thanks for pointing it out @dereuromark. Done :)

**Comment by dereuromark** [comment]
:+1:
