### ISSUE TITLE
Could not load class MonologLoggerLog

### ISSUE THREAD

**Issue by stevenmc** [jadb/cakephp-monolog#6]
Following the install instructions with PHP Version 5.4.9-4ubuntu2.2 (Ubuntu 13.04) CakePHP 2.4.0-RC1  I got the following error:

```
Could not load class MonologLoggerLog
Error: An Internal Error Has Occurred.
Stack Trace
CORE/Cake/Log/LogEngineCollection.php line 42 →     LogEngineCollection::_getLogger(string)
CORE/Cake/Log/CakeLog.php line 199 → LogEngineCollection->load(string,     array)
APP/Config/monolog.php line 28 → CakeLog::config(string, array)
APP/Config/bootstrap.php line 27 → require(string)
CORE/Cake/Core/Configure.php line 92 → include(string)
CORE/Cake/bootstrap.php line 177 → Configure::bootstrap(boolean)
APP/webroot/index.php line 82 → include(string)
```

This was resolved by changing Lib/Log/Engine/MonologLogger.php from:

```
class MonologLogger extends BaseLog {
```

to:

```
class MonologLoggerLog extends BaseLog {
```

I don't want to do a pull request in-case this causes problems for other environments.  Just an FYI.

Thank you,
Steven

**Comment by jadb** [comment]
@stevenmc 

You seem to have misconfigured your logger. 

Have you explicitly passed the `engine` key with a `Monolog.MonologLogger` value when configuring it?
